version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725477831.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest 851725477831.dkr.ecr.us-east-1.amazonaws.com/auth:latest
  post_build:
    commands:
      - docker push 851725477831.dkr.ecr.us-east-1.amazonaws.com/auth:latest
