steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sempio-dev/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
