services:
  phoenix:
    hostname: phoenix
    container_name: phoenix
    build:
      context: .
      dockerfile: ./apps/phoenix/Dockerfile
      target: development
    command: pnpm run start:dev phoenix
    env_file:
      - ./apps/phoenix/.env
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app

  auth:
    hostname: auth
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3002:3002'
      - '3003:3003'
    volumes:
      - .:/usr/src/app
      
  mongo:
    image: mongo