apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: 851725477831.dkr.ecr.eu-west-1.amazonaws.com/auth:latest
          name: auth
          env:
            - name: MONGODB_URI
              value: mongodb+srv://root:toor@sempio-dev-api.cnbslww.mongodb.net/auth
            - name: JWT_SECRET
              value: Ad76kOylO3iFt9GPKU0z7M1MiVNtDIRPiBjM3hBPNkF7tQLT17Wx6ns3MkySnhAQ
            - name: JWT_EXPIRATION
              value: '14400'
            - name: RT_SECRET
              value: 3dwaq1ed2rf3tgy4huj5ik6ol7p8ok9ij8uh7yg6tf5rd4es3wa2q1
            - name: RT_EXPIRATION
              value: 7d
            - name: TCP_PORT
              value: '3002'
            - name: HTTP_PORT
              value: '3003'
          ports:
            - containerPort: 3002
            - containerPort: 3003
